language: node_js
sudo: false
node_js:
- 5
- 4
- '0.12'
- iojs
matrix:
  include:
  - node_js: 6
    env: DEPLOY=true
after_success: if [[ $DEPLOY == "true" ]] ; then ./node_modules/.bin/gulp condensation:deploy
  ; else echo "no deploy" ; fi
env:
  global:
  - secure: WavADmtNoXmjnDvYr4EJXjjZPFKa3xWAD/Is4aSL0V7c+OwCR4NbD2h/DY84jCp95NMpPvgwCQdPLvPdLzxR4tUp6uXHzEf4BvyDtfdyi0gpElGHMnS3ijJ0eEoQcgiqe+q3i8qanQp0SHhZ/upRg+EfgkfQAmJ4ohiUlQ8eZi8GiJing97BD1H0C1quOwY0k/xo3iQ3LIHVKTXhSPqHji9Tq9hkb9g2a4cErpVEYF7/rdlHednJKkR06Kfq+Jj1WqVzFDU401zSPBs6dlvfXtNtYOogerbV/MVAluD+gjn9g+LeSDF0Z4hvVONrHTxLaI3S+PDq4xm0dqIZpTX7YbAk+auN0XqgDkkG59WXz/hdvWrcpbT3eKL/PoxjSrRFUbYVQmp9HLZVOC8x/cE5F/q4jHiDog2SuJBFb7zfICzjodretxTvzDwfNTYA0I6V1XXDRrsWTVmbraOLY/6BFhrjB+OcWMoktoFQEqtgqnKGixWTcR6A59brbiRAm+6EI/AxNKVk5YYL3PPfae1o//7LTnd6pyJ0WhhBS62TagXmTvdpjWbEdVUQXHQWcUMudLIFFX2JWCYg76P1x5I+OYGHAmvrySQ6aGrFCYoNz93Lp19340scuW0hUZenv2Ih0lN+q0RxGyhRSC559wvwDFHmd2BhnZJZF1mXpsi8L58=
  - secure: AaAKkjJcaYwaQmMUxrMF8YH6idPVoh8BtEK451q+ObMX7JXN1wtnH0R2kHmC51V5qpn7qLEY2HbEvEVYHjzU7Q+npTMsIX9OaP63NpasBgfElnmRZmBVodVMMsoRkdLCe053/smpVDuUXddqfRzMlbekjhB0l5RTRXbDmpXWBbthFRFp/HUtqZynjwNvpVHqdUuxsVdDLMqFFrV5o5N2xp+z8KZvyauDxpqltDUl/L8gkrWThGsgBhZJkoOhuPiOjZVrJWrXH9M37puPunMH54s1E3N5NGfNAFDANmdj4LbqtIaOxUgirqQOfcZ7Nb/WI2inIvtHasgHd9rJl5O5gQM1q9/aLxWRC/x2fEV5aLa5Cx4O36KFSzZFf6/7sFsKQv2Z89MaFMw1k7MsCTiARNW01oDiH101lGItIssH7FXkCwsYW3UbqtnSWcGrXP8yxkbiFqkFJ45z1N1R5r9NDG9LN5AEKTy8nsAbIwa+AGd0S4sh4sHxQnxQsr7RCLYTk/1BmeCHz9v2tx12Hu23jUuWJTHeU5p5T+3DTdYNPpuOAMxPOe8hYV70VBcYSPGNdlnxl3VscqwYRnQ+YX2QUXqnl5jkMATzTooSHU6dPRQHSKBqaL7ypZTC5v71k3TPvq4whktFGsgzAzL3txws/XOu0w4LfNX1BESo2YwFwPo=
deploy:
  provider: npm
  email: as.us.labs@sungardas.com
  api_key:
    secure: xQzwCOlt0sRh+pq4O7OEckRudN5B/a8nfG7LCFQ9eujI4LRq1EnixsJp0ipsyr8a46C6pW7qkG6Gd9CFiCo8adr5/qtcgMkhEMlIhWAaBsCmPoD0+GBgfBE+HVGkPW0sb2yF3LyJobNRK42ldEAlwP4DfgxyZF2WPFCYrdjCm1Q04T5LSa37NNDBqJo5qoMGPlnKELxJYAIElPJ1IOC4Sylw4MOVO+x3wFAPVOWEUAdqOMJRgJtBXF0HcwH/44Jd2VhJn24K1hIkie2lta6CyJcu+NBbq14z/OmX/HbctUHTShHzLWc24+3BCNbE2jUZaE6S+W3xAH59ofjgPfYHvqxcf8V9wcv7VRYVFGiheytN6SL7FKAV+h1Il7jlTKroxH76ryUyYog0XcVUUyvZTQnS2U0epjP3vCW6u97UeeT+9xBBwzPK9vDFRZ8BvxBbxqCI2Ll6C81/cPCZo+d8zsrTLpQI6OFVSk8Dfq89xrHES4pf0k+5L6gdRiz9ri2MaY4OIz48cCETsRUxVQLU6crTzT8kDUShYfes3pL7LvzhYMWajPiteOCwO4OEP8LLWAwif6m6X8kXYEUSHzqvvB9Vj3p143yVdJK1G6CA+dEDndOATKTkfNrmgyqomDH9ZO6H8qsCXSiMnhmPrXo3Y6UgwF5WqssbNFszhjm8rf0=
  on:
    tags: true
    repo: SungardAS/particles-rds
    node: 6
